questionText = 'What is the bicycle crash density in the area? (bicycle crashes/sq. mile)'
useUrl = 'Bicycle Crash - Use bicycle crash data map'
url = 'https://experience.arcgis.com/experience/e3fc453ef32d41819135f2b0d6e5c78d'
answers = [
  { text = '0-4', points = 1.0 },
  { text = '5-7', points = 2.0 },
  { text = '8-10', points = 3.0 },
  { text = '11-15', points = 4.0 },
  { text = '15+', points = 5.0 },
]
answerLeadingHeader = 'Crashes:'
domain = 'Crash'
autoFillEnabled = true
buttonText = 'Bicycle Crash'
instructionsMarkdown = '''
* Click on the link for Nevada Pedestrian and Bicyclist Crash Data 2019-2024, available [here](https://experience.arcgis.com/experience/e3fc453ef32d41819135f2b0d6e5c78d).
* Enter an address within the project area into the search bar on the left top corner of the map and click on the magnifying glass.
* To properly view the project area, click the minus (–) button located in the top-left corner of the map.
* Bicycle crashes are represented by red dots on the map. The legend should be visible by scrolling through the sidebar on the bottom right corner.
* Click the “POLYLINE” tool option from the right sidebar to draw a line along the project's exterior perimeter. Left click at a point on the map to begin drawing. Left click again at the end of each segment. Double-click to complete the drawing. (Note: This may be different for Mac and PC users.)
* Ensure “0.25” appears in the first box and “miles” appears in the second box on the right sidebar.
* A blue shape with a 0.25-mile radius will appear around the area. You may need to zoom out to view it fully. 
* The bicycle crash density should automatically populate on the right-side menu.
* Return to the PST to select the appropriate range of values within which your density value falls.
'''
videoId = '1lK8xJY703WTE5kfYKCR-Zlaz5JiwH5R_'
hint = ''
