questionText = 'How many bike lanes and shared use paths are in the area or within 1/4 mile radius?'
useUrl = 'Bike lanes and shared use paths: Use RTC data'
url = 'https://experience.arcgis.com/experience/21cefdd1b0004349ab370a348afdea4b/'
answers = [{ text = '0', points = 0.0 }, { text = '1 or more', points = 4.0 }]
answerLeadingHeader = 'Number:'
domain = 'Connectivity'
autoFillEnabled = true
buttonText = 'Bike Lanes'
instructionsMarkdown = '''
* Access the RTC Bike Lanes Map, available [here](https://experience.arcgis.com/experience/21cefdd1b0004349ab370a348afdea4b/).
* Click on the “Map Layers” icon on the information bar. Ensure that the boxes for “Enhanced Bicycle Lane,” “Bicycle Lane,” and “Shared Use Path” are checked, and uncheck the remaining boxes.
* Click on “Legend” (icon with 3 horizontal lines) in the top right of the menu to reveal how “Enhanced Bicycle Lane,” “Bicycle Lane,” and “Shared Use Path” appear on the map, then exit that menu.
* Click the magnifying glass icon at the top right of the map, then enter the project area address in the search bar and press enter.
* Zoom in and out (as needed) using the (+) and (-) buttons on the top left of the map until the map displays about 1/4 mile in each direction from the project area. 
* Click on the “Measure” button near the magnifying glass (a ruler with two arrows above it)
  * Click on a point within the project area closest to a bicycle lane or shared use path and then drag the measurement line to the lane or path to reveal the distance.
  * Ensure “Miles” is set as the unit of measurement (in a drop-down menu slightly to the right).
  * Continue this process until it is clear if there are 0 or 1 or more bicycle lanes and/or shared use paths within 1/4 mile.
* Select the answer below that corresponds to the number of bicycle lanes and/or shared use paths located within 1/4 mile of the project area.
'''
videoId = '1K5qUtMPqAvlCFuPzC5s7mN9oLYOSdGWO'
hint = ''
