questionText = 'What is the level of bus service within a quarter mile of the project area, considering how often buses come and whether riders have shade while they wait?'
useUrl = 'Use the RTC Bus Stop map,'
url = 'https://experience.arcgis.com/experience/16014bc5f0e64eabb604339a6a3898d1'
answers = [
  { text = '0-.75', points = 0.0 },
  { text = '0.76-1.5', points = 1.0 },
  { text = '1.6-2', points = 2.0 }
  ]
answerLeadingHeader = 'Number:'
domain = 'Connectivity'
autoFillEnabled = false
buttonText = 'Bus Stops'
instructionsMarkdown = '''
* Click the link for the RTC Bus Stop map, available  [available here](https://experience.arcgis.com/experience/16014bc5f0e64eabb604339a6a3898d1).
* In the search box on the top left of the map, enter the address for the project area and click on the magnifying glass or press enter.
* Zoom in and out (as needed) using the (+) and (-) buttons on the top left of the map.
* Use the “Draw Area” button on the right sidebar to draw the shape of the project area.
  * Left click at a point on the map to begin drawing. Left click again at the end of each segment. Double-click to complete the drawing. (Note: This may be different for Mac and PC users.)
  * The bus stop accessibility score will appear in a blue box on the right toolbar.
* Enter the answer below that corresponds to the number of parks located within ½ mile of the project area.
'''
videoId = '1-c5E25TSebN_3inZxxgYGgwjpCXezn7u'
hint = ''
