questionText = 'What is the average Microscale Audit of Pedestrian Streetscapes (MAPS) Mini score for all of the segments in the project area?'
useUrl = 'Conduct MAPS Mini for each segment in person and then average them to get a MAPS mini score.'
url = 'https://www.drjimsallis.com/maps'
answers = [
  { text = '0-1', points = 0.0 },
  { text = '2-3', points = 2.0 },
  { text = '4-5', points = 4.0 },
  { text = '6-7', points = 6.0 },
  { text = '8-9', points = 8.0 },
  { text = '10-11', points = 10.0 },
  { text = '12-13', points = 12.0 },
  { text = '14-15', points = 14.0 },
  { text = '16-17', points = 16.0 },
  { text = '18-19', points = 18.0 },
  { text = '20', points = 20.0 },
]
answerLeadingHeader = 'MAPS Mini Score:'
domain = ''
autoFillEnabled = false
buttonText = ''
instructionsMarkdown = '''
Note: The MAPS Mini Survey may also be completed using online maps, though the information may not be as up-to-date.
* Click the link provided for the MAPS Mini Survey, [available here](https://www.drjimsallis.com/maps).
* Click the box on the left-hand side of the page that is labeled “MAPS Mini.”
  * You should review the “MAPS Mini Protocol and Picture Guide” before going on to the next section. The guide provides necessary field procedures for the user to understand how to answer survey questions correctly.
* Click on the MAPS Mini Survey
* Complete the MAPS Mini Survey for each segment - i.e., block. Average the MAPS Mini points for all segments.
* Use the MAPS Mini Points to derive and record the corresponding PST points.
'''
videoId = '1zUzgSCSfwZu3MJGTe3hWTMy7qyol7_sq'
hint = ''
