questionText = 'What is the National Walkability Index Score?'
useUrl = 'Use EPA National Walkability Score'
url = 'https://epa.maps.arcgis.com/apps/mapviewer/index.html?webmap=f16f5e2f84884b93b380cfd4be9f0bba'
answers = [
  { text = '1-5.75', points = 3.125 },
  { text = '5.76-10.50', points = 6.25 },
  { text = '10.51-15.25', points = 9.375 },
  { text = '15.26-20', points = 12.5 },
]
answerLeadingHeader = 'Index:'
domain = ''
autoFillEnabled = true
buttonText = 'Walkability Index'
instructionsMarkdown = '''
* Click the link provided for the U.S. Environmental Protection Agency (EPA) National Walkability Score, [available here](https://epa.maps.arcgis.com/apps/mapviewer/index.html?webmap=f16f5e2f84884b93b380cfd4be9f0bba).
* Click on the magnifying glass in the bottom right of the map. Enter the address for the project area inside the text box that appears and hit enter.
  * Zoom in or out on the map to view entire project area. Note where the project area is located, as the circle indicator may disappear.
* On the left, click on "Basemap" (the icon with four small squares) and select "Imagery Hybrid."
* Click on "Legend” in the top left corner. You may need to first select the icon of three dots beneath Basemap.
* Cross-reference color(s) in the project area with the color/number range listed.
  * If the project area straddles multiple color-coded zones, find the exact average by clicking on each block group in the project area and obtaining the “Walkability Index” score for each zone. Add those scores together and divide by the number of zones to find the final calculation.
* Select the corresponding National Walkability Score.
'''
videoId = '19obFWR3mjn556N2jDPB41fkWJvMUqn66'
hint = ''
